import os

from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("PASSWORD_ALGORITHM")
MONGODB_URL = os.getenv("MONGODB_URL")

VONAGE_API_KEY = os.getenv("VONAGE_API_KEY")
VONAGE_API_SECRET = os.getenv("VONAGE_API_SECRET")
VONAGE_APPLICATION_ID = os.getenv("VONAGE_APPLICATION_ID")
VONAGE_APPLICATION_PRIVATE_KEY_PATH = os.getenv("VONAGE_APPLICATION_PRIVATE_KEY_PATH")
WORKING_VONAGE_API_KEY = os.getenv("WORKING_VONAGE_API_KEY")
WORKING_VONAGE_API_SECRET = os.getenv("WORKING_VONAGE_API_SECRET")
WORKING_VONAGE_APPLICATION_ID = os.getenv("WORKING_VONAGE_APPLICATION_ID")
WORKING_VONAGE_APPLICATION_PRIVATE_KEY_PATH = os.getenv("WORKING_VONAGE_APPLICATION_PRIVATE_KEY_PATH")

VONAGE_SIGNATURE_SECRET = os.getenv("VONAGE_SIGNATURE_SECRET")
RABBIT_VHOST = os.getenv("RABBIT_VHOST")
RABBIT_USER = os.getenv("RABBIT_USER")
RABBIT_PASSWORD = os.getenv("RABBIT_PASSWORD")
APP_ENVIRONMENT = os.getenv("APP_ENVIRONMENT")
SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = os.getenv("SMTP_PORT")
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
SMTP_DOMAIN = os.getenv("SMTP_DOMAIN")
FRONTEND_URL = os.getenv("FRONTEND_URL")
MESSAGE_STATUS_URL = os.getenv("MESSAGE_STATUS_URL")
MESSAGE_REPLY_URL = os.getenv("MESSAGE_REPLY_URL")
